# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee87f14ab7d0ecc30793ae899730dd7a43bda67a09c4d366ffcf94a7127fe9f77cdea7fb714899d73c7f484fd953fcac01748d940461ecdb957674bf43e34a6

test:
  secret_key_base: 05655be8e370ede6bf7da345599eb4144c4db33d509d82f61e6383c50bdc809890d4509a89661eb0fe48b94a0f6f298b4abf740ba86db04d479711ab5a7231fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
